from __future__ import annotations

STATUS_ENTWURF = "Entwurf"
STATUS_IN_BEARBEITUNG = "In Bearbeitung"
STATUS_WARTET = "Wartet auf Unterlagen"
STATUS_ABSCHLUSSPRUEFUNG = "Abschlusspruefung"
STATUS_ABGESCHLOSSEN = "Abgeschlossen"
STATUS_ABGESCHLOSSEN_BYPASS = "Abgeschlossen (Bypass)"

ACTION_START = "start"
ACTION_WAIT_FOR_DOCUMENTS = "wait_for_documents"
ACTION_TO_REVIEW = "to_review"
ACTION_COMPLETE = "complete"
ACTION_BYPASS_COMPLETE = "bypass_complete"
ACTION_SET_TASK_STATUS = "set_task_status"
ACTION_RUN_PYTHON_TASK = "run_python_task"
ACTION_EXPORT_FILE_TASK = "export_file_task"
ACTION_GENERATE_PRINT_TASK = "generate_print_task"
ACTION_CONFIRM_PRINT_TASK = "confirm_print_task"
ACTION_CREATE_LINKED_DOC = "create_linked_doc"

STATUS_TRANSITIONS = {
	(STATUS_ENTWURF, ACTION_START): STATUS_IN_BEARBEITUNG,
	(STATUS_IN_BEARBEITUNG, ACTION_WAIT_FOR_DOCUMENTS): STATUS_WARTET,
	(STATUS_IN_BEARBEITUNG, ACTION_TO_REVIEW): STATUS_ABSCHLUSSPRUEFUNG,
	(STATUS_WARTET, ACTION_TO_REVIEW): STATUS_ABSCHLUSSPRUEFUNG,
	(STATUS_ABSCHLUSSPRUEFUNG, ACTION_COMPLETE): STATUS_ABGESCHLOSSEN,
	(STATUS_ABSCHLUSSPRUEFUNG, ACTION_BYPASS_COMPLETE): STATUS_ABGESCHLOSSEN_BYPASS,
}

TERMINAL_STATES = {STATUS_ABGESCHLOSSEN, STATUS_ABGESCHLOSSEN_BYPASS}


def get_target_status(current_status: str, action: str) -> str:
	return STATUS_TRANSITIONS.get(((current_status or "").strip(), (action or "").strip()), "")


def is_status_action(action: str) -> bool:
	return action in {
		ACTION_START,
		ACTION_WAIT_FOR_DOCUMENTS,
		ACTION_TO_REVIEW,
		ACTION_COMPLETE,
		ACTION_BYPASS_COMPLETE,
	}


def is_task_action(action: str) -> bool:
	return action in {
		ACTION_SET_TASK_STATUS,
		ACTION_RUN_PYTHON_TASK,
		ACTION_EXPORT_FILE_TASK,
		ACTION_GENERATE_PRINT_TASK,
		ACTION_CONFIRM_PRINT_TASK,
		ACTION_CREATE_LINKED_DOC,
	}
